version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: music_school_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: music_school
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - music_net

volumes:
  postgres_data:

networks:
  music_net:
    driver: bridge
